// <auto-generated />
namespace Migx.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Relacionamentoamigousuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relacionamentoamigousuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231544194_Relacionamento amigo usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
