// <auto-generated />
namespace Migx.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campoemprestadonoitemdatimeline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campoemprestadonoitemdatimeline));
        
        string IMigrationMetadata.Id
        {
            get { return "201611241853336_Campo emprestado no item da timeline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
